[package]
name = "maze_walker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "maze_walker"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
png = "0.17.5"